### ISSUE TITLE
Allow factory reset of Philips Hue Zigbee Light Link (ZLL) devices through TouchLink?

### ISSUE THREAD

**Issue by Hedda** [zigpy/zigpy#1468]
Feature request for "ZLL Touchlink" support (also known as "Zigbee Light Link Touch Link" or "Touchlinking") but not sure this request only belongs in [zigpy](https://github.com/zigpy/zigpy) or also in the [zha](https://github.com/zigpy/zha) library as an API as well as in [zigpy-cli](https://github.com/zigpy/zigpy-cli) as a CLI (command-line interface) tool for zigpy or a combination of some or all of those, but regardless think this feature should be added to Home Assistant’s [ZHA integration](https://www.home-assistant.io/integrations/zha) Zigbee Gateway application (which depends on all these zigpy libraries/projects). 

For reference, Zigbee2MQTT do feature some user-friendly touchlinking functions if using a compatible Zigbee Coordinator adapter:

* https://www.zigbee2mqtt.io/guide/usage/touchlink.html

Primarly just looking for Z2M's user-friendly way to factory reset of IKEA and Philips Hue Zigbee Light Link (ZLL) devices through TouchLink, specifically lightbulbs and LED-strips (i.e. basic lighting products) from IKEA and Philips as they do not have buttons for reseting them, which makes them a pain to factory reset:  

* https://github.com/Koenkk/zigbee2mqtt/issues/2396

  * https://e2e.ti.com/support/wireless-connectivity/zigbee-thread-group/zigbee-and-thread/f/zigbee-thread-forum/570609/cc2538-how-to-trigger-a-zll-device-reset-using-znp-3-0

Allowing such commands in zigpy could in theory also enable features such as joining/pairing Philips products using serial number:

* https://github.com/Koenkk/zigbee2mqtt/issues/3492

  * https://github.com/Koenkk/zigbee2mqtt/issues/3492#issuecomment-625982938

It would of course ge most awesome if the ZHA integration could both reset and pair supported Zigbee devices via Touchlink! 😄 

* https://community.silabs.com/s/article/how-to-add-a-device-to-centralized-network-via-touch-link?language=en_US

Anyway, for the sake of making consumer lighting applications a more user-friendly experience for users who are new to Zigbee (and/or the ZHA integration in Home Assistant), please consider adding support for Touchlink commisioning and Touchlink factory resetting older Philips Hue Zigbee Light Link (ZLL) devices through Touchlink (using Zigbee touchlinking method like Zigbee2MQTT’s zigbee-herdsman feamwork and the hue-thief script can do) as that would make it much more user-friendly to pair/join Philips Hue bulbs with older firmware that has previously been added to another Zigbee Gateway (like example the official Philips Hue Bridge) but then not been properly removed and reset. 

Check out this stand-alone "Hue Thief Skyconnect" Python script by johnneerdael:

* https://github.com/johnneerdael/hue-thief-skyconnect

Which in turn was weavily inspired by hue-thief from vanviegen but also includes a lot of changes:

* https://github.com/vanviegen/hue-thief 

hue-thief (which looks to currenly only be working with a Silicon Labs EmberZNet/EZSP-based Zigbee adapters) is a Python script that can also be used factory reset Hue devices through Touchlink. After a such factory reset, the devices can then easily join any type of compatible Zigbee gateway.

"_**Hue Thief will scan all Zigbee channels for ZLL-compatible bulbs that are associated with any Zigbee network. When a bulb is found, it will blink a couple of times, and the application will ask if you want to factory reset this bulb. (If you didn't see any blinking, you may be doing your neighbours a favour by choosing 'N' here. :-)) That's it. Your now factory clean bulbs should be discoverable through whatever means your bridge/software offers.**_"

* https://www.zigbee2mqtt.io/guide/usage/touchlink.html#factory-reset-device

  * https://www.zigbee2mqtt.io/guide/usage/touchlink.html

Demo video showing Zigbee2mqtt factory reset Hue bulb with Touchlink:

* https://www.youtube.com/watch?v=kcRj77YGyKk

Problem to solve:  Philip Hue devices with older firmware can be a real pain to factory reset if you do not have the official Philips Hue Bridge because they deviated from the official Zigbee specification, so older Philip Hue lightbulbs are only capable of being factory reset via Touchlink, and as such it is not possible to factory reset such older Philip Hue devices by just pressing a hardware reset-button or use the more common power-cycle reset method (i.e. simply turn the power off and on to the device in a certain order with correct timing a with most other Zigbee devices.

* https://www.zigbee2mqtt.io/guide/usage/touchlink.html

As it stands right now ZHA end-users have to jump through some hops before they can properly pair/join a previously used such Philips Hue lightbulb device to ZHA if they do not still have their official Philips Hue Bridge, and the current workarounds is to either use a Hue compatible remote or dimmer switch product or hue-thief reset the bulb/light via Touchlink. Only after a such factory reset can such older Philips Hue bulbs easily join ZHA (or other compatible Zigbee gateway).

Those workarounds are covered in ZHA docs under troubleshooting here:

* https://www.home-assistant.io/integrations/zha#add-philips-hue-bulbs-that-have-previously-been-added-to-another-bridge

Having this feature would especially make it much easier for new users migrate from a Philips Hue Bridge to the ZHA integration:

* https://community.home-assistant.io/t/migrating-from-a-philips-hue-bridge-to-the-zha-zigbee-home-automation-integration/620862

Again, you might also want to consider adding support for ZLL TouchLink commissioning which can allow users to commission and pair a TouchLink capable Zigbee device by simply putting it in very close physical proximity to the Zigbee Coordinator and selecting "TouchLink commissioning" to start exchanging keys, which is known “Touchlinking" in the Zigbee Light Link (ZLL) specification, (downside to having a such feature is that it is at risk of a security attack during the touchlink commissioning procedure):

* https://www.silabs.com/documents/public/user-guides/ug103-09-fundamentals-zll.pdf

Various keys used in ZLL Commissioning Plug-in in EmberZNet PRO stack:

  * https://community.silabs.com/s/article/various-keys-used-in-zll-commissioning-plug-in-in-emberznet-pro-stack?language=en_US

PS: You should also be aware of the Z3sec project which uses touchlink to hack comprised devices via a touchlink security exploit:

* https://github.com/IoTsec/Z3sec/blob/master/README.md

**Comment by johnneerdael** [comment]
https://github.com/johnneerdael/hue-thief-skyconnect

I've made a heavily modified version specifically for the skyconnect intended to run on win (or Mac using a virtualized ubuntu for instance (done using UTM here on a M3), all parameters are preset for the skyconnect.

I've also a lot more output logging:

```sh
python3 hue-thief.py /dev/ttyUSB0
Initializing device...
Configuring radio parameters...
Radio EUI64: 00:21:2e:ff:ff:08:30:c4
Started manufacturing library mode

Scanning on channel 11 (attempt 1/3)
Sending scan request...

Scanning on channel 11 (attempt 2/3)
Sending scan request...

Scanning on channel 11 (attempt 3/3)
Sending scan request...

Scanning on channel 12 (attempt 1/3)
Sending scan request...

Scanning on channel 12 (attempt 2/3)
Sending scan request...

Scanning on channel 12 (attempt 3/3)
Sending scan request...

Scanning on channel 13 (attempt 1/3)
Sending scan request...

Scanning on channel 13 (attempt 2/3)
Sending scan request...

Scanning on channel 13 (attempt 3/3)
Sending scan request...

Scanning on channel 14 (attempt 1/3)
Sending scan request...

Scanning on channel 14 (attempt 2/3)
Sending scan request...

Scanning on channel 14 (attempt 3/3)
Sending scan request...

Scanning on channel 15 (attempt 1/3)
Sending scan request...

Scanning on channel 15 (attempt 2/3)
Sending scan request...

Scanning on channel 15 (attempt 3/3)
Sending scan request...

Scanning on channel 16 (attempt 1/3)
Sending scan request...

Scanning on channel 16 (attempt 2/3)
Sending scan request...

Scanning on channel 16 (attempt 3/3)
Sending scan request...

Scanning on channel 17 (attempt 1/3)
Sending scan request...

Scanning on channel 17 (attempt 2/3)
Sending scan request...

Scanning on channel 17 (attempt 3/3)
Sending scan request...

Scanning on channel 18 (attempt 1/3)
Sending scan request...

Scanning on channel 18 (attempt 2/3)
Sending scan request...

Scanning on channel 18 (attempt 3/3)
Sending scan request...

Scanning on channel 19 (attempt 1/3)
Sending scan request...

Scanning on channel 19 (attempt 2/3)
Sending scan request...

Scanning on channel 19 (attempt 3/3)
Sending scan request...

Scanning on channel 20 (attempt 1/3)
Sending scan request...

Scanning on channel 20 (attempt 2/3)
Sending scan request...

Scanning on channel 20 (attempt 3/3)
Sending scan request...

Scanning on channel 21 (attempt 1/3)
Sending scan request...

Scanning on channel 21 (attempt 2/3)
Sending scan request...

Scanning on channel 21 (attempt 3/3)
Sending scan request...

Scanning on channel 22 (attempt 1/3)
Sending scan request...

Scanning on channel 22 (attempt 2/3)
Sending scan request...

Scanning on channel 22 (attempt 3/3)
Sending scan request...

Scanning on channel 23 (attempt 1/3)
Sending scan request...

Scanning on channel 23 (attempt 2/3)
Sending scan request...

Scanning on channel 23 (attempt 3/3)
Sending scan request...

Scanning on channel 24 (attempt 1/3)
Sending scan request...

Scanning on channel 24 (attempt 2/3)
Sending scan request...

Scanning on channel 24 (attempt 3/3)
Sending scan request...

Scanning on channel 25 (attempt 1/3)
Sending scan request...

Scanning on channel 25 (attempt 2/3)
Sending scan request...

Scanning on channel 25 (attempt 3/3)
Sending scan request...

Scanning on channel 26 (attempt 1/3)
Sending scan request...

Scanning on channel 26 (attempt 2/3)
Sending scan request...

Scanning on channel 26 (attempt 3/3)
Sending scan request...
```

**Comment by Hedda** [comment]
> https://github.com/johnneerdael/hue-thief-skyconnect
> 
> I've made a heavily modified version specifically for the skyconnect

Any chance you consider looking into porting it as a feature inside the zigpy-cli as a tool and/or add an API for it to the zha library so that it can then be used by Home Assistant’s ZHA integration component via its UI?

https://github.com/zigpy/zigpy-cli

https://github.com/zigpy/zha

https://github.com/home-assistant/core/tree/dev/homeassistant/components/zha

Alternativly as a new feature for the zha-toolkit if the zigpy developers do not want that code inside a zigpy project?

https://github.com/mdeweerd/zha-toolkit

https://community.home-assistant.io/t/zha-toolkit-a-big-set-of-zigbee-commands-on-top-of-zha-zigpy/373346

**Comment by johnneerdael** [comment]
> > https://github.com/johnneerdael/hue-thief-skyconnect
> > I've made a heavily modified version specifically for the skyconnect
> 
> Any chance you consider looking into porting it as a feature inside zigpy-cli or zha library and ZHA integration component for UI?
> 
> https://github.com/zigpy/zigpy-cli
> 
> https://github.com/zigpy/zha
> 
> https://github.com/home-assistant/core/tree/dev/homeassistant/components/zha
> 
> Alternativly as a new feature for the zha-toolkit if the zigpy developers do not want that code inside a zigpy project?
> 
> https://github.com/mdeweerd/zha-toolkit
> 
> https://community.home-assistant.io/t/zha-toolkit-a-big-set-of-zigbee-commands-on-top-of-zha-zigpy/373346

Honestly I found most reliable way for Philips bulbs to do following power cycle till it resets: 2s off, 8s on, 2s off, 5s on and repeat a few times, worked every time. On traditional devices you just power cycle 6 times in a row quickly.

**Comment by janeswingler** [comment]
I'm working on this

**Comment by puddly** [comment]
This is tricky to implement and will require a ton of changes to zigpy, unfortunately. We effectively have to disable the radio for the entire duration of the scan and will need a new API to switch the adapter into inter-PAN mode. This is likely something we can add to zigpy-cli, however, and possibly to ZHA as an action once the API is stabilized.

We added the TouchLink clusters to zigpy at some point in the past (https://github.com/zigpy/zigpy/blob/dev/zigpy/zcl/clusters/lightlink.py) but the problem here is the radio API. I think we can extend the `ZigbeePacket` type to include optional `pan_id` and `channel` fields and then have a context manager like this?

```python
async with app.interpan_mode():
    await app.set_interpan_channel(11)
    await app.send_interpan_packet(...)
```

For actually receiving packets, however, `app.wait_for_response` will need to be amended to work with inter-PAN packets, since we assume all communication is done device-to-device with known devices on the current network, not ephemeral nodes like this.

**Comment by A-Mundanilkunathil** [comment]
## Touchlink Reset Implementation Question

Hi @Puddly,

I wanted to check if I'm on the right track with implementing **Touchlink reset** in `zigpy` and exposing it via **ZHA**.

We're working on this as part of **Code Day** and I'm collaborating with @janeswingler and @justin2186 on this implementation.

---

## Current Setup

I've cloned and am working locally with:
- `home-assistant/core`
- `zigpy/zha`
- `zigpy/zigpy`
- `zigpy/zigpy-cli`
- `zigpy/bellows` and `zigpy/znp` (to explore both radio paths)

**Hardware:**
- SONOFF ZBDongle-P (CC2652P)
- Home Assistant Connect ZBT-1 (EFR32MG21)

**Test devices:**
- GE Link BR30
- IKEA TRÅDFRI E26

*(Both should support Touchlink reset)*

---

## Implementation Plan

### 1. Add inter-PAN mode support to zigpy core:
- [ ] Add an `interpan_mode()` context manager in `zigpy.application.ControllerApplication`
- [ ] Add abstract `_enter_interpan_mode()` and `_exit_interpan_mode()` methods to the radio interface
- [ ] Add Touchlink service methods (`touchlink_scan()`, `touchlink_reset_device()`) to `ControllerApplication`

### 2. Add the necessary inter-PAN mode controls to the radio libraries (bellows, znp):
- [ ] Implement `_enter_interpan_mode()` and `_exit_interpan_mode()` in both radio libraries
- [ ] Handle channel switching and PAN ID management for inter-PAN operations

### 3. Use zigpy-cli to prototype the command and verify the hardware works

### 4. Once working, wire it up as a ZHA service (e.g. `zha.touchlink_reset`) in Home Assistant

---

## Additional Considerations

Since `zigpy.zcl.clusters.lightlink` already exists, I was also wondering:

> Should I be thinking about implementing a more formal **"Touchlink service"** class/module that uses those LightLink cluster commands, or is there a preferred way you'd envision this being integrated into the Zigpy architecture?

---

## Questions

- **Does this approach seem sound**, or am I misunderstanding any part of how inter-PAN packets should flow through the stack?
- **What's your preferred approach** for handling cases where the radio doesn't support inter-PAN mode or Touchlink operations?

Any guidance, validation, or red flags you can point out would be greatly appreciated — thank you again for all your work on this ecosystem!

**Comment by puddly** [comment]
I hate to speculate but the above comment seems to have been generated with AI. If so, I do want to warn you that zigpy, ZHA, and the radio libraries are (unusually) complex codebases and don't work well with existing AI tooling without serious amounts of prompting. You're free to experiment but please test things with a real device and a real coordinator before opening any PRs.

That being said, ignore Z-Stack (its inter-PAN implementation is very buggy and will probably crash the adapter) and just target EmberZNet 7.4.4.0. There's no issue raising errors if an adapter doesn't support features, we primarily target EmberZNet anyways.

**Comment by A-Mundanilkunathil** [comment]
Hi @puddly, We appreciate the feedback, it helped alot. Myself, @justin2186, and @janeswingler were assigned this issue as part of the CodeDay/CTI summer open source experience program. 

We are trying to see how far we can get on this feature request. We went ahead with a SONOFF ZBDongle-E (EFR32MG21) and are trying things out in the zigpy and bellows codebases. 

We see that packet processing is tightly coupled to known devices within the current network. To handle interpan packets we could refactor the existing flow extensively or maybe bypass with a wait_for_interpan_response() method to layer interPAN logic alongside. 

Since this will require so many additions/changes, we are wondering if that is something you would be open to including in zigpy.

Is there a smaller piece we could take on that could still help move this forward? We would love to contribute to the overall goal. 

Please feel free to share any thoughts or suggestions.

**Comment by puddly** [comment]
Sure! We definitely appreciate the help. Zigpy is a very...organic codebase so you've definitely picked a challenge 😄.

---

This is a very involved change overall so I think it would be best to cut it up into small, independent stages. The most approachable problem right is having *some way* to send and receive packets independent of the device API. As you mentioned, packets are tightly tied to devices and we assume that every packet is coming from a known device, with device objects themselves dealing with dissecting the packet into ZCL/ZDO commands.

The simplest way I can see this moving forward is by first actually creating a generic packet *reception* API for zigpy.

Maybe something like this, as a start?

```python
def callback(packet):
    print("Received a packet", packet)

# Address-specific callback
cancel1 = app.register_packet_callback(
    # The filter can be a `AddrModeAddress`, which wraps Group/NWK/IEEE/Broadcast addressing
    AddrModeAddress(addr_mode=AddrMode.NWK, address=NWK(0x1234)),
    callback,
)

# Global callback
cancel2 = app.register_packet_callback(None, callback)

# Call `cancel1()` and `cancel2()` to unregister them
```

This can be added without altering any existing zigpy APIs.

Once that's done, I think the next step would possibly be to break out ZCL parsing into a simple-to-use function so that it can be used without access to a device or clusters. This would allow for the TouchLink cluster commands to be processed using just the packet callback interface.

**Comment by Hedda** [comment]
While this is all way too low-level stuff for me I am still wondering if it might be a good idea to look how Touchlink is handled in the [zigbee-herdsman](https://github.com/Koenkk/zigbee-herdsman) which is used by the [zigbee2mqtt](https://github.com/Koenkk/zigbee2mqtt) application as they have implemented factory reset via Touchlink feature? Maybe for reference see:

https://github.com/search?q=repo%3AKoenkk%2Fzigbee-herdsman%20touchlink&type=code

and

https://github.com/search?q=repo%3AKoenkk%2Fzigbee2mqtt%20touchlink&type=code

As mentioned, from an end-users perspective please do check out how ZLL Touchlink is handled in the Zigbee2MQTT application:

* https://www.zigbee2mqtt.io/guide/usage/touchlink.html

PS: Zigbee2MQTT allows to factory reset devices through Touchlink. This is especially handy for e.g. Philips Hue bulbs as they cannot be factory reset by turning them on/off 5 times (like you can do on many Zigbee devices from other manufacturers). Watch this demo:

* https://www.youtube.com/watch?v=kcRj77YGyKk

1. _To factory reset a device through Touchlink bring the device close (< 10 cm) to your Zigbee Coordinator (e.g. Zigbee USB adapter). After this send a MQTT message to zigbee2mqtt/bridge/request/touchlink/factory_reset with an empty payload._
2. _Zigbee2MQTT will now start scanning, this can take up to 1 minute and during this scan your network cannot be used. After some time the device will identify itself (e.g. a bulb will start to blink)._
3. _Now that your device has been factory reset, it will automatically join Zigbee2MQTT (make sure that joining is enabled through permit_join: true). If it doesn't, try powering the bulb off and on 1 time._
4. _In case you want to factory reset a specific device (which can be found through a scan, see above) request the factory reset with the following payload: {"ieee_address": "0x12345678", "channel": 12}._

**Comment by janeswingler** [comment]
Hi @puddly, thanks again for the guidance. Before we proceed with a PR, @justin2186, @A-Mundanilkunathil and I would like to confirm our plan for the first step:

- Add a new `register_packet_callback()` method to `ControllerApplication`. This will accept an optional `AddrModeAddress` filter and a callback function, allowing callers to register for raw ZigbeePacket objects. It will return a cancellation function to unregister the callback.

- Add `self._packet_callbacks` in `ControllerApplication` for separate storage for these callbacks.

- Add a `notify_packet_callbacks()` helper method. This will accept a packet and be responsible for iterating through and executing the registered callbacks. It will first run all global callbacks and then address-specific callbacks.

I’m assuming the integration point for `notify_packet_callbacks()` will be at the top of `packet_received()` before device lookup logic? If so, should we modify `packet_received()` in our initial PR?

Please let us know if you have any thoughts or feedback.

**Comment by Hedda** [comment]
_Originally posted by @janeswingler in https://github.com/zigpy/zigpy/issues/16432_
> _Callback functions are called synchronously - async support could be added later as use cases develop. API is WIP **and could be extended for more filters (cluster/profile ID etc)**._
> 
> _**Next, we will implement standalone parsing utilities for packet processing independent of device and cluster objects, enabling TouchLink cluster command processing using this packet callback interface.**_

@janeswingler, @justin2186, @A-Mundanilkunathil what will be your next step now that your https://github.com/zigpy/zigpy/pull/1643 pull request has been merged?

 _Originally posted by @puddly in [#1468](https://github.com/zigpy/zigpy/issues/1468#issuecomment-3141563947)_
> _The simplest way I can see this moving forward is by first actually creating a generic packet reception API for zigpy. This can be added without altering any existing zigpy APIs. ... **Once that's done, I think the next step would possibly be to break out ZCL parsing into a simple-to-use function so that it can be used without access to a device or clusters. This would allow for the TouchLink cluster commands to be processed using just the packet callback interface**._

**Comment by janeswingler** [comment]
Hi, thanks for checking in @Hedda! Now that it has been merged I am working on standalone ZCL/ZLL parsing to handle Touchlink frames. After that I'm thinking to implement the interpan mode context manager and then implement those methods in the bellows radio library.

**Comment by Hedda** [comment]
FYI, for reference, it looks like Zigbee2MQTT's developers started working on something related for their zigbee-herdsman library:

* https://github.com/Koenkk/zigbee-herdsman/pull/1556 

  * https://github.com/Koenkk/zigbee2mqtt/issues/3492#issuecomment-625982938
 
* https://github.com/Koenkk/zigbee-herdsman/pull/1559

  * https://github.com/Koenkk/zigbee2mqtt/pull/29730

  * https://github.com/Koenkk/zigbee-herdsman-converters/pull/10800

    * https://github.com/Koenkk/zigbee-herdsman/pull/1663

  * https://github.com/Koenkk/zigbee-herdsman/pull/1727

**Comment by Mstrodl** [comment]
The serial number reset was frighteningly easy to implement. Seems like you just broadcast that ZCL frame on all channels and the hue light should leave its current network and try to join the one specified in the EPAN ID if it's open.

**Comment by Hedda** [comment]
> Now that it has been merged I am working on standalone ZCL/ZLL parsing to handle Touchlink frames. After that I'm thinking to implement the interpan mode context manager and then implement those methods in the bellows radio library.

@janeswingler, @justin2186, @A-Mundanilkunathil any updates on those next steps to make this more accessible to users of ZHA?

Have you already begun the work to add the interpan mode context manager to zigpy and the bellows radio library? Follow-up question is if you plan to expose it through zigpy-cli first so it can be tested/verified end-to-end against real lightbulb (there using a dedicated Zigbee adapter that is not used for anything else) before touching zha?

PS: Off-topic, but for refenence, some newer IKEA devices has dual-protocols support where their Zigbee protocol feature Touchlink:

* https://matter-smarthome.de/en/products/how-ikea-masters-the-combination-of-thread-and-zigbee/

As such Zigbee Touchlink can officially be used to reset both old and new Zigbee devices

* https://www.howtogeek.com/some-new-ikea-matter-over-thread-smart-home-devices-have-a-hidden-trick/

Unoffically it also means you can at least directly bind a new IKEA light and buttons devices to an old Zigbee one using Touchlink:

* https://community.home-assistant.io/t/ikea-just-announced-21-new-affordable-matter-over-thread-smart-home-devices-which-may-also-support-zigbee-too/948187
